### ISSUE TITLE
[Backend] : Get all user for admin role

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#100]
## Issue

We want that admin can get to know who all are enrolled in their course or for now, who all signup for the course

## Solution

Make a endpoint that gets all the users ( name, email, role, createdAt )

Request : POST
Endpoint: /getAllUsers

Note: Add admin and isAuthenticated middleware in route

- [x] JWOC

**Comment by Anushkabh** [comment]
@anand-harsh  i want to work under JWOC. kindly assign

**Comment by Anushkabh** [comment]
@anand-harsh  request should be GET?

**Comment by anand-harsh** [comment]
> @anand-harsh request should be GET?

yes

**Comment by Anushkabh** [comment]
@anand-harsh kindly review the pr #105
