### ISSUE TITLE
[Enhance] : Display courses in frontend

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#101]
## Issue

We don't have courses available displayed on frontend

## Solution

Display all courses in (http://localhost:3000/courses) in the fronted, with proper card and a dummy image for now, or maybe you can ignore image part for now

### Prerequisite : #102 

- [x] JWOC

**Comment by vishal2005025** [comment]
I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I Would Like to Work in This issue Under JWOC 2024
