### ISSUE TITLE
[Backend] : Get all available courses

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#102]
## Issue

We want a endpoint which fetch only courses available in database

## Solution

Make a endpoint which gets all the courses with all its felid

Request : GET
Endpoint: /getAllCourses

- [x] JWOC

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I Would Like to Work on This Issue Under JWOC 2024

**Comment by Anushkabh** [comment]
@anand-harsh  i would like to work on this under jwoc

**Comment by Anushkabh** [comment]
@anand-harsh  completed , kindly merge if satisfied #106
