### ISSUE TITLE
Fix: Footer of Contact page

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#14]
Issue: Footer of contact ("/contact") page is not stick to bottom of page.

Ref: https://edumi-zeta.vercel.app/contact

**Comment by anand-harsh** [comment]
Ok @abhishek-kumar-91 I am assigning you this issue

**Comment by abhishek-kumar-91** [comment]
ok, thanks

**Comment by abhishek-kumar-91** [comment]
It's done @anand-harsh
