### ISSUE TITLE
Adding tailwind for better CSS styling

### ISSUE THREAD

**Issue by Mohit-Aasirwal** [anand-harsh/Edumi#19]
It is matter of hassle while we use vanilla css as it is so difficult to maintain it in larger codebases. it is recommended to use tailwind css in place of vanilla css to get our styles done at one place.

**Comment by anand-harsh** [comment]
Assigned @Mohit-Aasirwal

**Comment by anand-harsh** [comment]
Hi, Kindly update the fork again , due to some wrong commits previous codes were changed and now is updated.
