### ISSUE TITLE
Toggle buttons when clicked in Left Sidebar

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#2]
Header should close whenever any button is clicked.
Customise onClose in Buttons

**Comment by DeexithParand2k2** [comment]
Hi @anand-harsh , Can I take up this issue, can you kindly assign this to me. And can you give some more details on the above issue.

**Comment by hero-234** [comment]
> Hi @anand-harsh , Can I take up this issue, can you kindly assign this to me. And can you give some more details on the above issue.

Sure, So when any button on left sidebar is clicked , that page should open and left sidebar should get closed after any tab on it is clicked.

Hope its clear?

**Comment by anand-harsh** [comment]
> Hi @anand-harsh , Can I take up this issue, can you kindly assign this to me. And can you give some more details on the above issue.

Sure, So when any button on left sidebar is clicked , that page should open and left sidebar should get closed after any tab on it is clicked.

Hope its clear?

**Comment by DeexithParand2k2** [comment]
Thanks for assigning @anand-harsh. I'll look into it and let you know if I have any doubts on the issue.

**Comment by DeexithParand2k2** [comment]
Hi @anand-harsh. I'd been working on another hacktoberfest issue these days and got it merged. I'll start to work on this issue today onwards and will update you within next two days on the update. Thank you.

**Comment by DeexithParand2k2** [comment]
Hi @anand-harsh, I've fixed the bug and have made additional enhancements to the module. Kindly review and merge the PR as soon as possible. Thank you for the opportunity.

**Comment by anand-harsh** [comment]
Task Completed

**Comment by DeexithParand2k2** [comment]
Thanks @anand-harsh for the opportunity

**Comment by anand-harsh** [comment]
> Thanks @anand-harsh for the opportunity

I appreciate your contribution to this repo, looking to work on more issues
