### ISSUE TITLE
Scrollbar not sticking to right of the screen on small devices

### ISSUE THREAD

**Issue by zedgamer9128** [anand-harsh/Edumi#20]
The Scrollbar moves inward when on small screen as shown by the devtools.
![image](https://github.com/anand-harsh/Edumi/assets/33319711/54453996-1cdf-498c-9573-0dd2ee4f4baa)
And as you can see the text cuts off.

**Comment by anand-harsh** [comment]
Assined @zedgamer9128

**Comment by anand-harsh** [comment]
Hi, Kindly update the fork again , due to some wrong commits previous codes were changed and now is updated.

**Comment by zedgamer9128** [comment]
K
