### ISSUE TITLE
feature: #17 Add notes route

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#24]
Issue: Add "Notes" on the left sidebar and create a new route to it. Fill the content just as "Coming soon".
Note: Do not do proper CSS of that "Notes" page

PR is already there but due to some issue codebase got deleted and that PR was not merged properly
So just take code from PR #21 and add those codes here again

**Comment by code-bajju** [comment]
I'm in! I'll handle the "Notes" section, restore code from PR #21, and keep it clean according to my expertise. Assign me for this!

**Comment by code-bajju** [comment]
@anand-harsh can you please reply to me ?

**Comment by anand-harsh** [comment]
Assigned @code-bajju this issue
