### ISSUE TITLE
[Bug]: Explore button isn't working

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#26]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

no such versions affected.

### Platform and OS Version

no such as 

### Affected Devices

All

### Existing Issues

No

### What happened?

The "Explore" button on the website is currently non-functional, preventing users from accessing the explore functionality. This impacts the user experience and the intended navigation flow. We need to investigate and resolve this issue to ensure that users can seamlessly explore the content as intended.

### Steps to reproduce

1.Navigate to the website.
2.Locate and click on the "Explore" button.

### Expected behavior

The "Explore" button should lead users to the intended explore functionality, allowing them to explore relevant content.

### Attachments

<img width="433" alt="Screenshot 2024-01-11 at 12 40 07 AM" src="https://github.com/anand-harsh/Edumi/assets/136263179/caf27db4-dc77-4f0a-819a-53040361b40b">

### Screenshots or Videos

same as above.

### Additional Information

Verify the functionality across different browsers to ensure compatibility.
Test the button on various devices to confirm responsiveness.
Prioritize a quick resolution to enhance the user experience.
Let's collaborate to investigate and resolve the issue with the "Explore" button, ensuring a smooth and interactive browsing experience for our users.

**Comment by rahat2134** [comment]
@lusifer65  @zedgamer9128  @DeexithParand2k2  assign this issue to me.

**Comment by anand-harsh** [comment]
> @lusifer65 @zedgamer9128 @DeexithParand2k2 @anand-harsh assign this issue to me (after JWOC start and please don't close these issues right now Thank You).

Hi @rahat2134 you can proceed with it

**Comment by anand-harsh** [comment]
Wait for the coding period starts

**Comment by rahat2134** [comment]
Hmm, thanks. Very much curious to contribute.

**Comment by Sneha-Sonkar** [comment]
I would like to work on this issue under JWOC

**Comment by rahat2134** [comment]
@Sneha-Sonkar i am already done with the coding.

**Comment by Sneha-Sonkar** [comment]
> @Sneha-Sonkar i am already done with the coding.

so is the bug solved now? actually it was under jwoc and unassigned so I commented.

**Comment by rahat2134** [comment]
No, i haven't yet attempt the pull request.

**Comment by Sneha-Sonkar** [comment]
@rahat2134 does that mean that you haven't been assigned this issue yet?

**Comment by rahat2134** [comment]
Yup sort of.

**Comment by gayathrik23** [comment]
@anand-harsh can you assign me this issue under JWOC.. i would like to contribute

**Comment by rahat2134** [comment]
@anand-harsh thanks
