### ISSUE TITLE
[Feature]: (New Video) Replace Current Welcome Video with Relevant Content Video

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#27]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

The current welcome video on the website is a general introduction. To enhance user engagement and provide more relevant content, we propose replacing the existing video with one that aligns with the website's theme or content. This change will help in capturing the user's interest and delivering more value upon landing on the site.

### Problem

No, not as such serious issue but ya good to resolve it.

### Proposed Solution

Identify a relevant video that complements the website's content or theme.
Replace the current welcome video with the selected video.
Ensure proper embedding and functionality of the new video on the website.

### Alternatives Considered

Choose a video that aligns with the website's purpose and resonates with the target audience.
Verify the rights and permissions for using the selected video on the website.

**Comment by rahat2134** [comment]
<img width="988" alt="Screenshot 2024-01-11 at 12 50 34 AM" src="https://github.com/anand-harsh/Edumi/assets/136263179/3df86124-ef8b-4a1a-82cd-fc7de243f27e">
@zedgamer9128 @lusifer65 @DeexithParand2k2  assign this  to me.

**Comment by anand-harsh** [comment]
Hi @rahat2134 you can proceed with this issue

**Comment by gayathrik23** [comment]
@anand-harsh can you assign me this issue under JWOC.. i would like to contribute

**Comment by rahat2134** [comment]
@anand-harsh which type of video u want? any suggestions?

**Comment by anand-harsh** [comment]
> @anand-harsh which type of video u want? any suggestions?
> 

Video explaining what Edumi provides, like teachers can have courses on multiple domains and can add students to their class with access to videos, assignment management, and a private duscussion chatroom.
Rest you can have your suggestion too

**Comment by anand-harsh** [comment]
Hi @rahat2134 any updates?

**Comment by rahat2134** [comment]
@anand-harsh making of video would take time. I will try as fast as i can. Please reply me on discord.
