### ISSUE TITLE
[Bug]: Solve The Unresponsiveness & Bad UI in the admin's child routes

### ISSUE THREAD

**Issue by psykat1116** [anand-harsh/Edumi#28]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

0.1.0

### Platform and OS Version

None

### Affected Devices

All

### What happened?

Want to update the responsiveness of the admin's child routes like admin/user, admin/create-course, admin/add-course routes.

### Steps to reproduce

1. Just Add New Components and Update the UI
2. 
3. 
...

### Expected behavior

Similarly like admin/dashboard route

**Comment by anand-harsh** [comment]
Hi @psykat1116 , you can proceed with this

**Comment by anand-harsh** [comment]
Hi @psykat1116 a similar issue at #18 is already opened. So, I am closing this issue. You can open new issues or can work on the issue I will open till night.
