### ISSUE TITLE
[Feature]: Link Instagram and LinkedIn to admins account.

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#29]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

The enhanced feature now ensures that users are directed to the administrator's Instagram, LinkedIn, and YouTube profiles directly from the platform. Previously, the Instagram icon redirected users to their individual profiles, causing confusion. With this update, we have introduced clear and direct links to the admin's social media accounts.

Certainly! Below is an updated description for the revised feature:

Feature Description: Direct Link to Admin's Social Media Profiles

The enhanced feature now ensures that users are directed to the administrator's Instagram, LinkedIn, and YouTube profiles directly from the platform. Previously, the Instagram icon redirected users to their individual profiles, causing confusion. With this update, we have introduced clear and direct links to the admin's social media accounts.

Key Enhancements:

Instagram Icon Update:
The Instagram icon, which previously directed users to their personal profiles, now takes them to the official Instagram account of the platform administrator. This change provides users with a direct and authentic connection to the platform's leadership.

Introduction of LinkedIn and YouTube Icons:
In addition to Instagram, we have introduced LinkedIn and YouTube icons. Clicking on the LinkedIn icon will lead users to the administrator's LinkedIn profile, fostering professional connections. The YouTube icon directs users to the official YouTube channel, ensuring access to curated content and updates.

User-Friendly Navigation:
The updated icons and links offer a more intuitive and user-friendly navigation experience. Users can effortlessly connect with the administrator across multiple social media platforms directly from the platform.

How it Works:

Click on the Instagram icon to visit the administrator's official Instagram profile.
Navigate to the LinkedIn icon to connect with the administrator on LinkedIn.
Explore the YouTube icon to access the platform's official YouTube channel for videos and updates.

### Problem

Prior to the recent update, users experienced difficulty in directly accessing the administrator's official social media profiles from the platform. Specifically, the Instagram icon redirected users to their personal profiles, creating confusion and hindering the establishment of a direct connection with the platform's leadership.

### Proposed Solution

The introduced feature addresses these challenges by updating the Instagram icon to lead directly to the administrator's official account. Furthermore, the addition of LinkedIn and YouTube icons offers users clear pathways to connect with the administrator on these platforms, enhancing overall user engagement and communication.

### Alternatives Considered

can be alternatives but as of now its best.

**Comment by rahat2134** [comment]
@zedgamer9128  @lusifer65  @DeexithParand2k2 @anand-harsh assign this issue to me.

**Comment by anand-harsh** [comment]
Hi @rahat2134 you can proceed with this issue

**Comment by ayesha-2101** [comment]
@anand-harsh I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by gayathrik23** [comment]
@anand-harsh can you assign me this issue under JWOC.. i would like to contribute

**Comment by rahat2134** [comment]
@anand-harsh Thank you

**Comment by rahat2134** [comment]
Ok @anand-harsh  thanks, i will resolve this issue by eod.

**Comment by anand-harsh** [comment]
@rahat2134 , what changes you are going to make here?

**Comment by rahat2134** [comment]
i will connect your insta here also i will add a linkedIn tab which will ridirect to your linkedIn, linkedIn part will take time as i need to add logo,style,connection.

**Comment by anand-harsh** [comment]
Hi @rahat2134 , raise the PR asap, deadline about to end

**Comment by rahat2134** [comment]
@anand-harsh i need some more time, please respond to messages that i sent you on linkedIn and discord.

**Comment by anand-harsh** [comment]
Hi @rahat2134 , make it finish by 7:30pm, it's off the deadline now.

**Comment by rahat2134** [comment]
Sorry @anand-harsh it takes time,if you can assign me some more time. 🙂

**Comment by rahat2134** [comment]
Else just assign it to someone else. Thanks.

**Comment by rahat2134** [comment]
@anand-harsh thank u so much

**Comment by anand-harsh** [comment]
Hi @rahat2134 , deadline is up

**Comment by rahat2134** [comment]
@anand-harsh i am done with coding only need to merge pr..pls see discord for verification

**Comment by rahat2134** [comment]
@anand-harsh I message you at night also
