### ISSUE TITLE
Remove unwanted overflows

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#3]
improve footer width and formatting

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, Can you assign me?

**Comment by anand-harsh** [comment]
> I want to work on this issue, Can you assign me?

Hi @abhishek-kumar-91 , Footer has already been fixed, but you can work on removing the unwanted overflows on other pages. I am assigning you the issue.

**Comment by abhishek-kumar-91** [comment]
can you include the lebel of hacktoberfest-accepted

**Comment by anand-harsh** [comment]
Hi @abhishek-kumar-91 , are you still working on this issue?

**Comment by lusifer65** [comment]
I want to work on this issue, Can you assign me ?

**Comment by lusifer65** [comment]
can you please check and merge
