### ISSUE TITLE
[Feature]: Add images to sample courses and some dummy knowledge that looks good.

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#30]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

This feature introduces a visually appealing upgrade to course previews by incorporating engaging dummy sample images and enhancing the informational content. Previously, a basic box with minimal information left much to be desired. Now, learners can enjoy a more enticing preview that captures the essence of the courses.
(can add links that takes the user to youtube to particular channels )

### Problem

The previous state of course previews presented a challenge as it lacked visual appeal and provided minimal information. The absence of engaging visuals and informative content in the sample courses made it challenging for learners to make informed decisions and discover courses that piqued their interest.

### Proposed Solution

The introduction of dummy sample images and appealing information addresses these challenges by providing visually enticing placeholders and more informative content. This enhancement aims to create a more engaging and user-friendly course preview experience, facilitating better-informed decisions for learners.

### Alternatives Considered

Alternatively we can provide links to informative videos to youtube.

**Comment by rahat2134** [comment]
@anand-harsh assign this to me (JWOC).

**Comment by anand-harsh** [comment]
Hi @rahat2134 , I am sorry but you can have only 3 issues at once, after their successful merges or closing those issue can have new issues. I hope you understand

**Comment by rahat2134** [comment]
@anand-harsh please recheck it and assign it as medium if possible. I think it took time to enhance the course tab.

**Comment by anand-harsh** [comment]
Hi @rahat2134  these images will be fetched from backend and no youtube links will be there, the lectures will be uploaded by faculty

**Comment by rahat2134** [comment]
Hmm, i know but what i was saying was to add sample course layout. As i saw in the project in course section its not having a good layout so what i think to improve the layout.
And add 5-6 layout of different courses.

**Comment by anand-harsh** [comment]
Hi @rahat2134 , as this is not planned for now because of incomplete backend, So I have to close this issue for now. Maybe later, we can work on this.

**Comment by rahat2134** [comment]
> Hi @rahat2134 , as this is not planned for now because of incomplete backend, So I have to close this issue for now. Maybe later, we can work on this.

Ok @anand-harsh i feel happy to work with you in future. 🙂
