### ISSUE TITLE
Enhance: Footer design to be updated

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#32]
# Issue to be fixed:

Our footer is not looking professional and properly managed.

# Note: 

Propose a Footer with new UI and then after assigning to the best ones will get the issue assigned.
Footer should have quick links , socials, contributing link and should be responsive and interactive without fancy gradient colors

Open for JWOC' 24

**Comment by divyansh2375** [comment]
I want to work on this issue

**Comment by rahat2134** [comment]
assign it to me under jwoc

**Comment by akshitchowdhury** [comment]
I'm ready to get it done. You can rely on me to get it addressed

**Comment by akshwalia** [comment]
I'll get it done. Assign it to me.

**Comment by anand-harsh** [comment]
Hi @divyansh2375 , any updates?

**Comment by divyansh2375** [comment]
@anand-harsh  i am working on the issue actually the code was not cloning into my local system i also asked you in discord now i will be working on this issue

**Comment by divyansh2375** [comment]
![image](https://github.com/anand-harsh/Edumi/assets/130889408/16f4617e-c300-4dad-b358-65d42211444a)
i have successfully setup it locally into my system . now i am starting to work on the issue @anand-harsh

**Comment by anand-harsh** [comment]
Hi @divyansh2375 , its up the deadline. So you have been unassigned the issue, you can work on new issues

**Comment by Surajit0573** [comment]
I can work on this issue.... please assign me under JWOC 2024!!

**Comment by anand-harsh** [comment]
Hi @Surajit0573 , you need to implement the footer given in the links here

https://github.com/anand-harsh/Edumi/blob/master/Landing%20page.md
