### ISSUE TITLE
[Feature]:Improve Interface of Notes Tab and Add Sample Notes

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#33]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

<img width="613" alt="Screenshot 2024-01-13 at 2 04 08 PM" src="https://github.com/anand-harsh/Edumi/assets/136263179/6240f91b-00b1-4672-abe3-be68f05730f2">
The current interface of the Notes tab could benefit from improvements to enhance user experience. This feature request aims to make the Notes tab more visually appealing and user-friendly.

## Proposed Changes
1. **Interface Enhancement:**
   - Review and update the design of the Notes tab for a more modern and aesthetically pleasing appearance.
   - Ensure consistency with the overall application design.

2. **Sample Notes Addition:**
   - Introduce a set of sample notes to provide users with a starting point and showcase the functionality of the Notes tab.
   - Include notes with varying content and formatting to demonstrate the flexibility of the notes feature.

## Additional Information
Feel free to discuss and add any specific details, ideas, or mockups related to the proposed interface improvements and the sample notes.

## Acceptance Criteria
- The updated interface should be visually appealing and consistent with the application design.
- Sample notes should cover a range of scenarios and demonstrate key features.

### Problem

You are assigned the task of implementing the Notes tab for a Note-Taking application. The current state of the Notes tab displays a placeholder text "Coming Soon," but you are tasked with turning it into a fully functional and interactive section of the application.

### Proposed Solution

 we can to add samples notes section in notes tab , we can make sample layout with help of html and css also we can add sample pdf with them,
1. HTML Structure:
* Create a new section in your HTML file dedicated to the sample notes.
* Within this section, use HTML elements to structure each sample note, including titles, content, and links to sample PDFs.
2. CSS Styling:
* Style the sample notes section using CSS to achieve the desired layout.
* Apply CSS styles to the sample notes, ensuring a visually appealing and consistent design.
* Use CSS to create proper spacing, borders, and typography for each sample note.
3. Sample PDFs:
* Prepare sample PDF files that you want to include with the sample notes.
* Ensure that the PDFs are accessible through relative or absolute paths in your project.
4. Linking PDFs:
* Include anchor (<a>) tags within each sample note to link to the corresponding PDFs.
* Use the href attribute to point to the location of the sample PDFs.
* Optionally, set the target="_blank" attribute to open the PDFs in a new tab.
5. JavaScript (if needed):
* If you want to add dynamic behavior or interactivity to the sample notes section, you can use JavaScript.
* For example, you could use JavaScript to handle click events on the sample notes, providing additional functionality.

### Alternatives Considered

there can be various alternatives .

**Comment by rahat2134** [comment]
@anand-harsh assign this issue to me (one by one)

**Comment by harshsinghcs** [comment]
@rahat2134 if you want I'll help to solve this issue

**Comment by rahat2134** [comment]
@harshsinghcs i will let you know.

**Comment by harshsinghcs** [comment]
> @harshsinghcs i will let you know.

Sure let's connect:- linktr.ee/harshsinghcs
