### ISSUE TITLE
[Feature]: Add Favicon(logo) to Website.

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#34]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

The current version of the website is missing a favicon. A favicon is a small icon that represents the website and is displayed in the browser tab. Adding a favicon enhances the visual identity of the website and improves  the user experience.
<img width="216" alt="Screenshot 2024-01-13 at 2 10 22 PM" src="https://github.com/anand-harsh/Edumi/assets/136263179/d073c429-5422-4b02-9728-4088c63f38e4">

**Steps to Reproduce:**
1. Open the website in a web browser.
2. Observe that there is no favicon displayed in the browser tab.

**Expected Behavior:**
After the issue is resolved, a favicon should be visible in the browser tab when the website is accessed.

**Additional Information:**
- Ensure that the chosen favicon is clear and recognizable even at a small size.
- Test the website on different browsers to confirm the consistent display of the favicon.

### Problem

The current version of the website is missing a favicon. A favicon is a small icon that represents the website and is displayed in the browser tab. Adding a favicon enhances the visual identity of the website and improves the user experience.

### Proposed Solution

1. Design or obtain a suitable favicon for the website.
2. Save the favicon file in an appropriate format (e.g., .ico, .png).
3. Update the HTML code of the website to include the favicon.

### Alternatives Considered

..

**Comment by rahat2134** [comment]
@anand-harsh assign this to me (one by one).

**Comment by Divyanshgarg-04** [comment]
@anand-harsh can you please work on this issue

**Comment by ayesha-2101** [comment]
@anand-harsh I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by PushkarRai04** [comment]
Hey i would like to work on this project under JWOC

**Comment by ayesha-2101** [comment]
@anand-harsh I am willing to contribute to this under JWOC. Please assign it to me

**Comment by gayathrik23** [comment]
@anand-harsh can you assign me this issue under JWOC.. i would like to contribute

**Comment by humancoder1** [comment]
@anand-harsh , Hello Sir , I am interested in this issue , can you please assign this to me

**Comment by SHABIN-K** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by rahat2134** [comment]
@anand-harsh now u can assign this to me, all the pending pr done.(under jwoc)

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC. Can you please assign this issue to me

**Comment by purnamrita** [comment]
@anand-harsh I would like to work on this issue under JWOC, can you please assign it to me?

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I would like to Work on this issue under JWOC 2024

**Comment by anand-harsh** [comment]
Hi @rahat2134 , its up the deadline

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC once done with the other issue. Could you assign this

**Comment by rahat2134** [comment]
@anand-harsh assign this to anybody, quite busy in some stuff thank you.

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I am Ready With My PR Can I do?

**Comment by anand-harsh** [comment]
> Hey @anand-harsh Sir I am Ready With My PR Can I do?

yes
