### ISSUE TITLE
[Feature]: Enhance Sidebar with Icons and Titles.

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#36]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

The sidebar is a critical element of our website's navigation. To enhance its usability, we propose adding icons to each sidebar item. Icons can quickly convey the purpose of each section, making navigation more intuitive, especially for users who rely on visual cues.

**Steps to Reproduce:**
1. Access the website and observe the current sidebar.
2. Note the absence of icons next to the sidebar items.
3. After the enhancement, the sidebar should display icons alongside each item.

**Expected Behavior:**
Upon completion, users should see visually appealing icons next to each sidebar item, improving the overall navigation experience.

**Additional Information:**
- Icons should be consistent with the website's design and theme.
- Ensure icons are recognizable and convey the purpose of each section effectively.

**References:**
<img width="167" alt="Screenshot 2024-01-13 at 3 26 06 PM" src="https://github.com/anand-harsh/Edumi/assets/136263179/63afbb12-5f6a-4fab-a990-7a802a648cdc">

### Problem

The current sidebar lacks visual elements, making it less intuitive for users to navigate. Adding icons alongside the sidebar items, such as Home, will enhance the user experience and make navigation more engaging.

### Proposed Solution

Introduce icons for each sidebar item to complement the text titles. For example, use a home icon next to the "Home" item. This will improve visual recognition and create a more user-friendly interface.
**Tasks:**
1. Select appropriate icons for each sidebar item (e.g., Home, About, Services).
2. Update the HTML/CSS code to incorporate the selected icons.
3. Test the website to ensure the icons display correctly and align with the corresponding titles.
4. Optionally, consider hover effects or animations for a more interactive experience.

### Alternatives Considered

.

**Comment by ayesha-2101** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by rahat2134** [comment]
@anand-harsh assign the issue to me #JWOC .

**Comment by TejaswaniVelugoti** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by gayathrik23** [comment]
@anand-harsh  can you assign me this issue under JWOC.. i would like to contribute

**Comment by Jenis07** [comment]
Can you Please Assign me this issue Under JWOC?

**Comment by Prithwi32** [comment]
@anand-harsh I would like to work on this issue under JWOC

**Comment by anand-harsh** [comment]
Hi @rahat2134 , its up the deadline, so unassigning the issue.

**Comment by anand-harsh** [comment]
Hi @Prithwi32 you can go with this
