### ISSUE TITLE
[Feature]: Add Login & Signup option

### ISSUE THREAD

**Issue by Surajit0573** [anand-harsh/Edumi#37]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

After opening the website user goes through a sign-up or login process and then can access the website and personalized dashboard.

### Problem

![image](https://github.com/anand-harsh/Edumi/assets/111490250/196462c5-7864-4720-a97f-495af1d3f012)

Logout button is not working !!

### Proposed Solution

Users can either log in or sign up. New users will fill out a form and their data will be stored. Existing users will have their information verified. After a successful login, users can access a personalized dashboard where they can see their course and progress.

### Alternatives Considered

the website can also work without any login option but then the user can't access their course.

**Comment by Surajit0573** [comment]
Please assign me under JWOC after 15th, if approved.

**Comment by Surajit0573** [comment]
Please assign me this issue under JWOC 2024

**Comment by anand-harsh** [comment]
Hi @Surajit0573 the login and signup page is already there, u need to work on connecting the backend to its frontend for the Auth section.

**Comment by anand-harsh** [comment]
Hi @Surajit0573 any updates?

**Comment by anand-harsh** [comment]
Hi @Surajit0573  , as the deadline is over, I am unassigning you the issue.

This issue is opened to all now.

**Comment by Surajit0573** [comment]
> Hi @Surajit0573 , as the deadline is over, I am unassigning you the issue.
> 
> This issue is opened to all now.

@anand-harsh Okey,....sorry, I couldn't complete it in time...

**Comment by anand-harsh** [comment]
Hi @Surajit0573 , no worries, you can take up new issues

**Comment by JavidSumra** [comment]
Hey @anand-harsh I Would Like to Work on This Issue under JWOC 2024.

**Comment by JavidSumra** [comment]
Hi @anand-harsh, based on the information in this issue, it seems that I only need to create two pages: one for login and another for signup. Is my understanding correct?

**Comment by anand-harsh** [comment]
> Hi @anand-harsh, based on the information in this issue, it seems that I only need to create two pages: one for login and another for signup. Is my understanding correct?

Login and signup page is already there, just do isAuth to false, you will get it.

You need to connect backend to frontend here for signup and login.
React redux usage is preferred

**Comment by anand-harsh** [comment]
> Hey @anand-harsh Is it necessary to use Redux Toolkit or i can Do it with Simple `useState`?

Using react redux will make the fronrend control easy like having access and usafe limitations according to information

**Comment by JavidSumra** [comment]
Hi @anand-harsh, do I have to use Redux, or is it optional?

**Comment by JavidSumra** [comment]
Hey @anand-harsh Can You Please Tell me Exact Path of Sidebar?

**Comment by anand-harsh** [comment]
> Hey @anand-harsh Can You Please Tell me Exact Path of Sidebar?

It is present in Header file

**Comment by anand-harsh** [comment]
Hi @JavidSumra any updates?

**Comment by JavidSumra** [comment]
Both Functionality is implemented I just need to do PR.
