### ISSUE TITLE
[Feature]:  Add "Go to Top" Button to Website

### ISSUE THREAD

**Issue by rahat2134** [anand-harsh/Edumi#38]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

<img width="276" alt="Screenshot 2024-01-13 at 10 49 53 PM" src="https://github.com/anand-harsh/Edumi/assets/136263179/3d9b8410-0d77-416d-a570-064ad163ab6d">

The current version of the website lacks a "Go to Top" button, which can enhance user experience by providing a convenient way for visitors to quickly navigate back to the top of the page, especially on longer pages.

**Steps to Reproduce:**
Visit any long-scrolling page on the website.
Observe the absence of a "Go to Top" button.
After the issue is resolved, revisit the page and locate the newly added "Go to Top" button.
Click the button and confirm that the page scrolls smoothly to the top.
**Expected Behavior:**
Upon completion of the issue, the website should feature a visible and functional "Go to Top" button that enhances user navigation.

### Problem

User Navigation Difficulty:
Without a "Go to Top" button, users may find it inconvenient to manually scroll back to the top, especially on lengthy pages.

### Proposed Solution

Adding a "Go to Top" button provides a simple and user-friendly solution for quick navigation to the top of the page.

### Alternatives Considered

.

**Comment by rahat2134** [comment]
@anand-harsh assign this to me (one by one) #jwoc

**Comment by rahat2134** [comment]
@anand-harsh assign this issue firstly, as i have already code it only have to pull request, after this other issue.

**Comment by SGCODEX** [comment]
I would like to work on this issue under JWOC

**Comment by rahat2134** [comment]
@anand-harsh please check the pr and tell me any updation?

**Comment by anand-harsh** [comment]
Hi @rahat2134 , make this as component and add it to every page, mainly Dashboard, Browse all courses. Also try replacing text with a arrow image. Hope you get
