### ISSUE TITLE
Backend: Get specific course using id, having multiple lectures in a Course.

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#40]
# Issue: 
We need to get a specific course using course id which we will render in our courses list

# Solution: 
1) Make a component "getCourseLectures " where you will be getting the course from the id for that course by params ( /course/:id )
2) A course can have multiple lecture in its "lectures" array.
3) If anyone is opening the video then increase the views by 1

Request : GET
Route: /course/:id
Response: 200

- [x] JWOC

**Comment by mishra811** [comment]
Hi can you please assign me this issue under JWOC

**Comment by Anushkabh** [comment]
i would like to work under JWOC @anand-harsh

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC'24. Please assign this issue to me

**Comment by anand-harsh** [comment]
@Anushkabh you can go with it

**Comment by Anushkabh** [comment]
@anand-harsh  when views should increase by 1 ? like simply accessing the course or while opening lecture?

**Comment by anand-harsh** [comment]
> @anand-harsh when views should increase by 1 ? like simply accessing the course or while opening lecture?

If views are for course, increase it for course

**Comment by Anushkabh** [comment]
@anand-harsh okay I have implemented the same.. kindly check the pr
