### ISSUE TITLE
Backend : Add Lectures to specific course

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#41]
# Issue: 
Add lectures to the specific course playlist

# Solution: 
1) Make a component "addLecture"  where you take id in req.body
2) Take title, description from users.
3)  Handle errors and cases properly for already having lecture in course or course doesn't exist
4) After successful addition of lecture in the course, increase " numVideos " by 1.

Request : POST
Route: /course/:id

- [x] JWOC

**Comment by Anushkabh** [comment]
@anand-harsh  i would like to work on this. kindly assign under JWOC
i am proficient in backend development

**Comment by Anushkabh** [comment]
@anand-harsh kindly merge if satisfied
