### ISSUE TITLE
Backend: Make authorisation middleware for admin role

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#42]
# Issue 
As anyone can add course to playlist or remove it from playlist, so we do not want this full authority to be given to users

# Solution
1) Make a middleware "adminAuthorisation" for the admin with role.
2)  If user is having role "admin" then only he can perform the task of addition or deletion.
3) if any user without admin role tries to do the task then return "Not Allowed" with 403 status code.
4) Add middlewares to " /createcourse" and POST request for " /course/:id"

- [x] JWOC

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC. Van you please assign this issue to me

**Comment by Divyanshgarg-04** [comment]
@anand-harsh /course/:id route is not defined

**Comment by anand-harsh** [comment]
> @anand-harsh /course/:id route is not defined
> 

In API (backend)

**Comment by Divyanshgarg-04** [comment]
<img width="344" alt="image" src="https://github.com/anand-harsh/Edumi/assets/120127517/0c853430-7439-4e4f-a180-7f2348a3d81d">

in courseRoutes.js file there are only two routes defined

**Comment by Divyanshgarg-04** [comment]
@anand-harsh It should be get request rather than post?

**Comment by anand-harsh** [comment]
> @anand-harsh It should be get request rather than post?

We are not making crud operation here so need of post or get. We are making middleware which will be later used in get or post request routes to limit the access of normal user to that route.

Here what you can do is, take token from cookie, decode that token to get id, check the role for that id, if the role of that id is admin, return next() else return ErrorHandler("cant access") with a status code.

Hope you get it
