### ISSUE TITLE
Backend : Delete a specific lecture from the course 

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#43]
# Issue: 
Want to delete a specific lecture from the course playlist

# Solution: 
1) Make a component "removeFromCoursePlaylist" where you will be getting the id for that course by params ( /course/:id )
2) After successful deletion , return "Lecture deleted successfully " with status code 200.
3) Handle Errors and edge cases properly.

Request : DELETE
Route: /removefromplaylist

- [x] JWOC

**Comment by Anushkabh** [comment]
@anand-harsh i would like to work on this. kindly assign under JWOC

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would like to work on this issue under JWOC'24 once my PR gets accepted. Please assign this to me

**Comment by Divyanshgarg-04** [comment]
@anand-harsh Can you assign this issue to me now under JWOC

**Comment by anand-harsh** [comment]
> @anand-harsh Can you assign this issue to me now under JWOC

Hi, without completing #41 , this issue cant be assigned.
I am making your name as in waitlisted for this issue.

After #41 is completed, you will be assigned this issue
Till then you can work on other issue or wait for its completion

Remember, 1 user can be assigned only 1 issue

**Comment by Divyanshgarg-04** [comment]
Can I start working on issue #41 If you allow under JWOC

**Comment by Anushkabh** [comment]
@Divyanshgarg-04 I am working on #41 . Will push it today

**Comment by Divyanshgarg-04** [comment]
ok

**Comment by JavidSumra** [comment]
Hey @anand-harsh i would like to work on this. kindly assign under JWOC.

**Comment by anand-harsh** [comment]
@Divyanshgarg-04 you can go with it

**Comment by Divyanshgarg-04** [comment]
ok

**Comment by Divyanshgarg-04** [comment]
@anand-harsh In this issue, route will be course/:id or /removefromplaylist ?

**Comment by anand-harsh** [comment]
> @anand-harsh In this issue, route will be course/:id or /removefromplaylist ?
> 
> <img alt="image" width="610" src="https://private-user-images.githubusercontent.com/120127517/297962196-b0120db1-1cc8-4b4e-86a0-e11cee5dd7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM1NTcsIm5iZiI6MTcwNTY0MzI1NywicGF0aCI6Ii8xMjAxMjc1MTcvMjk3OTYyMTk2LWIwMTIwZGIxLTFjYzgtNGI0ZS04NmEwLWUxMWNlZTVkZDdkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNTQ3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzhiNDJhYjRkNWEyYzM3YWYzYTBmMDExNDE5NmUwODU4MzRjN2E0OGFiMDY3MmI0MTg3MzU3MWE3N2NhYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GcIiqnhDTIErtsKESk0fOmA18g5VHrLCmvBeOooCU2E">

There was a confusion regarding this. Issue is that no logic is there to add course to personal playlist. I will raise a issue for that first
