### ISSUE TITLE
Backend : Get all users (Admin Controller)

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#44]
# Issue: 
We need to get all users in the admin side to manage them properly.

# Solution: 
1) Make a component "getAllUsers" 
2) Add "adminAuthorise" and "isAuthenticated" middlewares to its route

Request : GET
Route: /admin/users

- [x] JWOC

**Comment by Anushkabh** [comment]
@anand-harsh i would like to work on this. kindly assign under JWOC

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue too. Please assign this issue to me under JWOC'24
