### ISSUE TITLE
Backend : Delete any user (Admin Controller)

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#46]
# Issue: 
If the user cancel subscription or admin want to remove the user then we need to delete the user from our db (access to premium courses)

# Solution: 
1) Make a component "deleteUser" where you will be getting the id for that course by params ( /course/:id )
2) After successful deletion , return "User deleted successfully " with status code 200.
3) Handle Errors and edge cases properly.

Request : DELETE
Route: /admin/users/:id

- [x] JWOC

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC'24. Please assign this to me

**Comment by Divyanshgarg-04** [comment]
@anand-harsh Can you please assign this issue to me under JWOC'24 now
