### ISSUE TITLE
[Feature]: Add Modern Scrollbar

### ISSUE THREAD

**Issue by itsmeabhishek03** [anand-harsh/Edumi#47]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

I Can Add Modern Scrollbar Instead of default scrollbar 

### Problem

no

### Proposed Solution

will add some css
![image](https://github.com/anand-harsh/Edumi/assets/104294494/9f8e0f51-9283-455d-a9f4-8e46fb301417)

### Alternatives Considered

will add some css

**Comment by anand-harsh** [comment]
Hi @itsmeabhishek03 as it is a easy issue and it exceeded the 1 day deadline, so I have to assign this issue to other guy. You can work on other not-assigned issue.

**Comment by itsmeabhishek03** [comment]
> Hi @itsmeabhishek03 as it is a easy issue and it exceeded the 1 day deadline, so I have to assign this issue to other guy. You can work on other not-assigned issue.

I didn't know that there is something like deadline as it is my first open source contribution

**Comment by anand-harsh** [comment]
> > Hi @itsmeabhishek03 as it is a easy issue and it exceeded the 1 day deadline, so I have to assign this issue to other guy. You can work on other not-assigned issue.
> 
> I didn't know that there is something like deadline as it is my first open source contribution

Check out #31

**Comment by anand-harsh** [comment]
@itsmeabhishek03 I am assigning you again this, issue, Kindly acknowledge it as per deadline.
Assigned at 11:14am 16Jan

**Comment by itsmeabhishek03** [comment]
Okay thank you I will raise PR soon

**Comment by gitgoap** [comment]
Can you assign it to me! Thx @anand-harsh

**Comment by gitgoap** [comment]
I am working on this issue, it is taking a little longer!

**Comment by anand-harsh** [comment]
Hi @gitgoap take your time, make it by tomorrow night

**Comment by gitgoap** [comment]
Hey @anand-harsh 
Is the yellow color good for the scroll bar

![Screenshot 2024-01-20 160405](https://github.com/anand-harsh/Edumi/assets/117789470/4de65e1e-fd2b-427d-985c-7dec423c8864)

**Comment by anand-harsh** [comment]
> Hey @anand-harsh Is the yellow color good for the scroll bar?
> 
> ![Screenshot 2024-01-20 160405](https://private-user-images.githubusercontent.com/117789470/298276622-4de65e1e-fd2b-427d-985c-7dec423c8864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTU0OTEsIm5iZiI6MTcwNTc1NTE5MSwicGF0aCI6Ii8xMTc3ODk0NzAvMjk4Mjc2NjIyLTRkZTY1ZTFlLWZkMmItNDI3ZC05ODVjLTdkZWM0MjNjODg2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxMjUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODNjMDdhMWJkM2NjODU3NWUwOWFiZThhZTM4ZDY5YjIyM2QxMmFhZDYxYTRjMDU5ZTM5NzE4ZTg2MzZhMzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gTrGAs2guPbnBEDFQJos2YvEmHljrgjb_bLiOSt5Acg)

make it orange, we are going to have new theme soon
