### ISSUE TITLE
Backend : Delete personal profile / account

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#48]
# Issue: 
Want to delete own profile or account

# Solution: 
1) Make a component "deleteMyprofile" where you will be getting the id for that user by params
2) After successful deletion , return "Profile deleted successfully " with status code 200.
3) Handle Errors and edge cases properly.
4) Delete the "token" from cookies and set cookies expires to Date.now() to logout user from current session.

Request : DELETE
Route: /me

- [x] JWOC

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue please assign this to me under JWOC'24

**Comment by anand-harsh** [comment]
Hi @Divyanshgarg-04 You can proceed with it

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I have to delete course or the user account

**Comment by anand-harsh** [comment]
> @anand-harsh I have to delete course or the user account

Account

**Comment by Divyanshgarg-04** [comment]
User in the profile component is hardcoded so should i take the imaginary id of the user to make a request to backend for deleting the account ("/me/:id")?

**Comment by Divyanshgarg-04** [comment]
@anand-harsh User in the profile component is hardcoded so should i take the imaginary id of the user to make a request to backend for deleting the account ("/me/:id")?

**Comment by anand-harsh** [comment]
> @anand-harsh User in the profile component is hardcoded so should i take the imaginary id of the user to make a request to backend for deleting the account ("/me/:id")?

No, this issue is only related to backend for making a rest api, it has no relation to frontend for now

**Comment by anand-harsh** [comment]
> @anand-harsh User in the profile component is hardcoded so should i take the imaginary id of the user to make a request to backend for deleting the account ("/me/:id")?

Use postman or thunderclient to make requests, not the frontend page
