### ISSUE TITLE
[UI] : Add Update Profile Page

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#49]
# Issue
The user need to make change in their profile information

# Solution
Make a interactive UI according to the theme of the website containing following details at " /profile/updateprofile "

- Name (required)
- Email (required)
- Organisation
- Contact Number (required)
- Address (required)
- Office Address
- Social - Linkedin, Github, Twitter, Instagram

with a submit button, after submitting, user should be redirected to /profile

**Comment by Aswinr24** [comment]
Hey would like to work on this issue under JWOC 2024

**Comment by anand-harsh** [comment]
Hi @Aswinr24 you can go with it

**Comment by anand-harsh** [comment]
Hi @Aswinr24 any updates?, deadline is almost over

**Comment by Aswinr24** [comment]
Sorry for responding late, I was busy with another issue till a day ago..Would try to make a PR by tomorrow afternoon If you accept

**Comment by anand-harsh** [comment]
Hi @Aswinr24 , as the deadline is up, you need to move to other issues

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC once my PR gets merged Could you please assign this issue to me

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?

**Comment by Divyanshgarg-04** [comment]
@anand-harsh Can you assign this issue to me

**Comment by anand-harsh** [comment]
Hi @Jenis07 , its up the deadline

**Comment by JavidSumra** [comment]
Hey @anand-harsh I would like to Work on this issue under JWOC 2024
