### ISSUE TITLE
Fix dashboard layout

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#5]
The right sidebar is not properly aligned and the charts section is also not in proper place.

One interested can take this issue

**Comment by rajvinder-kaur** [comment]
i wanna work on it

**Comment by anand-harsh** [comment]
OK @rajvinder-kaur , I am assigning you this issue

**Comment by anand-harsh** [comment]
Hi @rajvinder-kaur any update on the issue?
