### ISSUE TITLE
[Documentation] : Initialise a documentation

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#50]
# Issue
There isn't any  documentation present which have the clear information about the api routes

# Solution
Initialise a documentation in .md format having information of the api routes and controllers which are in code yet.

Document should contain the information: 

- Route
- Request body field names
- Responses with status codes

**Comment by rahat2134** [comment]
@anand-harsh want to work under JWOC.

**Comment by divyansh2375** [comment]
i am ready to work on this issue after the completion of the first issue

**Comment by rahat2134** [comment]
> Hi @rahat2134 , you need to complete all your opened issue to get assigned to new issue

Okay, i will let you know by EOD.

**Comment by Anushkabh** [comment]
I would like to work on this under JWOC @anand-harsh

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I would love to work on this issue under JWOC. can you please assign this issue to me

**Comment by Anushkabh** [comment]
@Divyanshgarg-04 i am working on it.. it's almost completed
