### ISSUE TITLE
[UI] : Enhance Go to top button

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#55]
# Issue
Color of Go to Top button is not having theme related to our website

# Solution
1) Change it so that in light mode it appears white arrow with yellow background and in dark mode it appears white arrow with black background
2) Also make the border radius to circle.

# Screenshot

![image](https://github.com/anand-harsh/Edumi/assets/94885893/ff46cccf-6f5a-4961-9d97-01bc9da1ff6b)

**Comment by nandita27iitp** [comment]
@anand-harsh pls assign this issue under Jwoc

**Comment by rahat2134** [comment]
@anand-harsh assign me this, i am very familiar with the codebase. will resolve this asap.

**Comment by anand-harsh** [comment]
> @anand-harsh assign me this, i am very familiar with the codebase. will resolve this asap.

Read rules at #31

**Comment by nandita27iitp** [comment]
![image](https://github.com/anand-harsh/Edumi/assets/94813932/ff4256e5-b143-440d-8b5a-b71dfd7a3116)

![image](https://github.com/anand-harsh/Edumi/assets/94813932/a4b0a23b-2436-44a0-9007-6d97e2364f09)

@anand-harsh pls review it

**Comment by anand-harsh** [comment]
> ![image](https://private-user-images.githubusercontent.com/94813932/297334006-ff4256e5-b143-440d-8b5a-b71dfd7a3116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODY0MTksIm5iZiI6MTcwNTQ4NjExOSwicGF0aCI6Ii85NDgxMzkzMi8yOTczMzQwMDYtZmY0MjU2ZTUtYjE0My00NDBkLThiNWEtYjcxZGZkN2EzMTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NTZlMDY2ZTcyNzczOTcxZjM0YTQ2MjU0MDc5ZTE3NjQ2MjY3MzI4YzRhZjE2NGE2MWNlYTNlYzQ3M2U2Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qig0kE7Y7_ZPqzTvF9MTZHbnTCozxbRCDRiyHy0oVhE)
> 
> ![image](https://private-user-images.githubusercontent.com/94813932/297334117-a4b0a23b-2436-44a0-9007-6d97e2364f09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODY0MTksIm5iZiI6MTcwNTQ4NjExOSwicGF0aCI6Ii85NDgxMzkzMi8yOTczMzQxMTctYTRiMGEyM2ItMjQzNi00NGEwLTkwMDctNmQ5N2UyMzY0ZjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YzY1Zjc3MDY0YjRjYzNhODA4MDU4MjllMzFkNzI2YjQ1M2QxMDI2OGM5NzNjNDIwNDU5MDNlZDllNjcwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QL3GxA0dU-xsn6Gfq0W33y3sRBwCNB7ZQ8B6qlBWhcM)
> 
> @anand-harsh pls review it

Perfect

**Comment by rahat2134** [comment]
> I have done the PR
@nandita27iitp 
its not visible here i think you have not mention the issue number, just mention **_fix issue:#issuenumber_**
