### ISSUE TITLE
[UI/UX] : Propose a new design for website in Figma

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#57]
## Issue
Our website is not having any proper color scheme and design

## Solution
Propose a new design for website in light mode in Figma. Have proper color scheme and the same components used as in our website

**Comment by ojetunji** [comment]
Can you share the link to the existing website and what you're looking to achieve with the redesign? I'll love to help out.

**Comment by anand-harsh** [comment]
> Can you share the link to the existing website and what you're looking to achieve with the redesign? I'll love to help out. 

https://edumi-zeta.vercel.app/

**Comment by anand-harsh** [comment]
> Can you share the link to the existing website and what you're looking to achieve with the redesign? I'll love to help out. 

Customisation in color and some graphics to be added. I dont have much design knowledge but ya

You can Open PR for every 3 pages, will be marked as hard for all

**Comment by ojetunji** [comment]
@anand-harsh Please assign this to me so I can share my exploration
