### ISSUE TITLE
[Bug]: Problem in Top button and image is not loading properly

### ISSUE THREAD

**Issue by tushargupta1504** [anand-harsh/Edumi#65]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

5.1

### Platform and OS Version

ios1 2.1

### Affected Devices

all

### What happened?

The top button is not properly aligned

### Steps to reproduce

1. fixing the code 
2. revie
3. fix
...

### Expected behavior

the proper alignment should be there

### Screenshots or Videos

![image](https://github.com/anand-harsh/Edumi/assets/138330699/31c397b6-b08e-4c5e-8e3f-ccb46d7adf6e)

**Comment by anand-harsh** [comment]
> I would like to work on this issue

If the assignee will not be able to resolve issue in given deadline mentioned at #31 , then it will be assigned to you

**Comment by anand-harsh** [comment]
Hi @tushargupta1504 , as per the deadline, you are unable to raise a valid PR, So I have to unassign the issue to you.

**Comment by anand-harsh** [comment]
@Redclawww you can go with it

**Comment by tushargupta1504** [comment]
Pls give me sometime

**Comment by Redclawww** [comment]
@tushargupta1504  are you talking about this button
![Screenshot 2024-01-19 203917](https://github.com/anand-harsh/Edumi/assets/80527836/2b0f365b-fc93-41e3-8a54-50ad0f2984ec)

**Comment by anand-harsh** [comment]
> @tushargupta1504 are you talking about this button ![Screenshot 2024-01-19 203917](https://private-user-images.githubusercontent.com/80527836/298109729-2b0f365b-fc93-41e3-8a54-50ad0f2984ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzY0NjksIm5iZiI6MTcwNTczNjE2OSwicGF0aCI6Ii84MDUyNzgzNi8yOTgxMDk3MjktMmIwZjM2NWItZmM5My00MWUzLThhNTQtNTBhZDBmMjk4NGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA3MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OGJjMGVkNjAyNzczNDg1MWY3NTk0NWEzNjljOTQxZGJkNWM3ZTM5ZjQxOWU1NTNhNjM2MTEyYjgzMDUzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDXQgmmEvPAZZkuE996QVZ_N2jNwFy-pVM1BK6PE_dU)

YES

**Comment by tushargupta1504** [comment]
Yes

**Comment by Redclawww** [comment]
I have been travelling for the past couple days can you just gimme 2 days today I'll get it done

**Comment by anand-harsh** [comment]
Hi @Redclawww , its up the deadline for easy issue.

**Comment by amanswarnakar** [comment]
Hey @anand-harsh, I would like to work on this issue under JWOC'24.
