### ISSUE TITLE
[Backend[ : Add course to personal playlist

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#71]
Issue:
Want to add a specific course to the playlist

Solution:
Make a component "addToPlaylist" where you will be getting the id for that course by params ( /course/:id )
After successful addition , return "Course added successfully " with status code 200.
Handle Errors and edge cases properly.
Request : POST
Route: /addToPlaylist

**Comment by anand-harsh** [comment]
Hi @Divyanshgarg-04 you can work on this first

**Comment by Divyanshgarg-04** [comment]
@anand-harsh Can you assign this issue under JWOC

**Comment by anand-harsh** [comment]
Hi @Divyanshgarg-04 any reason for closing the PR?

**Comment by Divyanshgarg-04** [comment]
@anand-harsh I have created a new PR can you please once check
