### ISSUE TITLE
[Backend] : Add lecture id with lecture adding to course

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#72]
Issue:
Add lectures id to the lecture when adding it to course

Solution:
There is a component "addLectureToCourse" which is adding lectures to the course by taking title and description.
Use "uuid4" or any id generating library to generate a random id and push it with the lecture while adding

Request : POST
Route: in routes > Course.js ```router.post("/course/:id", isAuthenticated, isAdminAuthenticated, addLectureToCourse);```

**Comment by Jenis07** [comment]
Can you assign me this issue under the JWOC?

**Comment by Jenis07** [comment]
sir is there any issue regarding to create the course beacause i cannot creating the course part...

**Comment by anand-harsh** [comment]
> sir is there any issue regarding to create the course beacause i cannot creating the course part...

show the error

**Comment by Jenis07** [comment]
![image](https://github.com/anand-harsh/Edumi/assets/100338684/ef3a9558-8975-473a-8fc9-4b732b7e7b26)
this is the create course page in that i have adding the course but it does not getting any update in the database and courses page.
![image](https://github.com/anand-harsh/Edumi/assets/100338684/dbfdd663-8447-43ee-80ed-7ff7356cb338)
screenshot of the database

**Comment by anand-harsh** [comment]
> ![image](https://private-user-images.githubusercontent.com/100338684/298087652-ef3a9558-8975-473a-8fc9-4b732b7e7b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MTUsIm5iZiI6MTcwNTY3MjUxNSwicGF0aCI6Ii8xMDAzMzg2ODQvMjk4MDg3NjUyLWVmM2E5NTU4LTg5NzUtNDczYS04ZmM5LTRiNzMyYjdlN2IyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxMzU1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mzk1NDQ4MDhkYzgwNjNiMDllZDNiZWM2NzAyNGY3ZmUxMWViZWMwOTI4ZjRlN2Y0NDg0M2FlNTZkZTMzYTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xun50MJc3ftEkll1ae6WJD451JsZ_JRBGz8ims6CZM8) this is the create course page in that i have adding the course but it does not getting any update in the database and courses page. ![image](https://private-user-images.githubusercontent.com/100338684/298087923-dbfdd663-8447-43ee-80ed-7ff7356cb338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MTUsIm5iZiI6MTcwNTY3MjUxNSwicGF0aCI6Ii8xMDAzMzg2ODQvMjk4MDg3OTIzLWRiZmRkNjYzLTg0NDctNDNlZS04MGVkLTdmZjczNTZjYjMzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxMzU1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmE2OTc1MjM3YzBiZjgwMTZhMWZiNWZlODBhZmRmYzBkZWE4OGNiNzc0ZmJmMDQzNTg3NjA2MTA0MTk2ZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GAxpFtBfJfVVjgn_dAKdXtItSKQC3Z8LXXF_Dm4Cx_w) screenshot of the database

Don't use frontend, its not connected yet, you need to work only on backend using postman to send requests and get api tested

**Comment by Jenis07** [comment]
![image](https://github.com/anand-harsh/Edumi/assets/100338684/dc012b66-630f-4d0c-a913-e3593b12f217)
sir is this good or i have to implement other id generating?

**Comment by anand-harsh** [comment]
> ![image](https://private-user-images.githubusercontent.com/100338684/298377875-dc012b66-630f-4d0c-a913-e3593b12f217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDYyNDEsIm5iZiI6MTcwNTg0NTk0MSwicGF0aCI6Ii8xMDAzMzg2ODQvMjk4Mzc3ODc1LWRjMDEyYjY2LTYzMGYtNGQwYy1hOTEzLWUzNTkzYjEyZjIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQxNDA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGFhNzEwOWViY2E2N2ZkMDcyMDAyMzczZTBhNTA3NWU0OGI2MjEyMzA5MWQyZGQ5NjI0YzkyODViMDQwZDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z4pRykSxJ6OVeDqYWVmf1KJH__UzUmoosmF53XZEqro) sir is this good or i have to implement other id generating?

its fine
