### ISSUE TITLE
[UI/UX] : Propose a new design for website in Figma

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#77]
## Issue
Our website is not having any proper color scheme and design

## Solution
Propose a new design for website in light mode in Figma. Have proper color scheme and the same components used as in our website

Components to be designed for this issue:

1) Contact (https://edumi-zeta.vercel.app/contact)
2) Profile (https://edumi-zeta.vercel.app/profile)
3) Course Page: (https://edumi-zeta.vercel.app/courses)

Edit in Landing.md in the PR

**Comment by anand-harsh** [comment]
Hi @ojetunji you can have this issue and continue your work

**Comment by debuuuu007** [comment]
Hey is this issue still open?

**Comment by debuuuu007** [comment]
If yes, please let me know as fast as possible.

Thank you.

**Comment by anand-harsh** [comment]
> If yes, please let me know as fast as possible.
> 
> Thank you.

This issue is a continuation of user previous issue, so that user is aggined that issue

**Comment by debuuuu007** [comment]
Ok fine.

**Comment by Redvey** [comment]
@anand-harsh  can I help in any other design?

**Comment by anand-harsh** [comment]
Hi @ojetunji any update on contact page?

**Comment by ojetunji** [comment]
> Hi @ojetunji any update on contact page?

It's been done since. Check the Figma file. It's in the PR 2 layer.

**Comment by anand-harsh** [comment]
> > Hi @ojetunji any update on contact page?
> 
> It's been done since. Check the Figma file. It's in the PR 2 layer.

Open a pr for merging
