### ISSUE TITLE
[Enhance] : Restrict dashboard feature only to admins

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#97]
## Issue:

We don't want that common users can view insights and have access to features of dashboard

## Solution

Show Dashboard and its features only to users having admin privileges in their role. 

Note: Must use react-redux to manage data and state WITH PROPER SLICER AND STORE.JS

- [x] JWOC

**Comment by JavidSumra** [comment]
Hey @anand-harsh I Would Like To Work on This Issue Under JWOC 2024

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I Would Like to Work on This Issue.
