### ISSUE TITLE
[Enhance] : Connect Create course feature to frontend

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#98]
## Issue

The create course feature at ( http://localhost:3000/admin/createcourse ) is not working on frontend

## Solution: 

Connect frontend of the above url to the backend of ( /createcourse )

- [x] JWOC

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I Would Like to Work on This Issue Under JWOC 2024

**Comment by Anushkabh** [comment]
@anand-harsh  I would like to work on this under JWOC
kindly assign

**Comment by Anushkabh** [comment]
@anand-harsh i would like to work on this issue.. kindly assign under jwoc

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir Please Provide me Our Backend API for Cors.

**Comment by anand-harsh** [comment]
> Hey @anand-harsh Sir Please Provide me Our Backend API for Cors.

You need to use backend url of localhost:4000 for that
