### ISSUE TITLE
[Enhance] : Show user list to admin

### ISSUE THREAD

**Issue by anand-harsh** [anand-harsh/Edumi#99]
## Issue

We need to know who all are enrolled in that course, or in short we want all the users in ( http://localhost:3000/admin/users )

## Solution

Connect this page to the backend ( /getAllUsers )

Make a UI as table where you have following fields

1) Name
2) Email
3) Role

### Prerequisite for this issue : #100 

- [x] JWOC

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir I Would Like To Work on This Issue Under JWOC 2024

**Comment by anand-harsh** [comment]
Hi @JavidSumra , let #100 be merged, then will assign you this issue

**Comment by JavidSumra** [comment]
Hey @anand-harsh, I've resolved the issue and submitted a pull request. Could you please assign it to me? I began working on this problem when you initially assigned it to me.

**Comment by anand-harsh** [comment]
Hi @JavidSumra , open new issue for fixing list for all users, as its not visible for now
